"""Initial market time series"""

import sqlalchemy as sa
from alembic import op

revision = "938168f88eae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("product_id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("npc_sell_price", sa.Float(), nullable=True),
        sa.Column("metadata_updated_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "snapshots",
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("received_at", sa.BigInteger(), nullable=False),
        sa.Column("tax_rate", sa.Float(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("normalization_version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    op.create_table(
        "candles",
        sa.Column("product_id", sa.String(length=160), nullable=False),
        sa.Column("price_type", sa.String(length=24), nullable=False),
        sa.Column("interval", sa.String(length=4), nullable=False),
        sa.Column("bucket_start", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("first_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("last_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("estimated_volume", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.PrimaryKeyConstraint("product_id", "price_type", "interval", "bucket_start"),
    )
    op.create_table(
        "product_snapshots",
        sa.Column("product_id", sa.String(length=160), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("insta_buy_price", sa.Float(), nullable=True),
        sa.Column("insta_sell_price", sa.Float(), nullable=True),
        sa.Column("best_ask", sa.Float(), nullable=True),
        sa.Column("best_bid", sa.Float(), nullable=True),
        sa.Column("buy_order_volume", sa.Float(), nullable=False),
        sa.Column("sell_offer_volume", sa.Float(), nullable=False),
        sa.Column("insta_buy_moving_week", sa.Float(), nullable=False),
        sa.Column("insta_sell_moving_week", sa.Float(), nullable=False),
        sa.Column("buy_order_count", sa.Integer(), nullable=False),
        sa.Column("sell_offer_count", sa.Integer(), nullable=False),
        sa.Column("spread", sa.Float(), nullable=True),
        sa.Column("spread_pct", sa.Float(), nullable=True),
        sa.Column("flip_profit", sa.Float(), nullable=True),
        sa.Column("flip_margin_pct", sa.Float(), nullable=True),
        sa.Column("estimated_hourly_profit", sa.Float(), nullable=True),
        sa.Column("estimated_hourly_volume", sa.Float(), nullable=False),
        sa.Column("npc_sell_price", sa.Float(), nullable=True),
        sa.Column("npc_ratio", sa.Float(), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.ForeignKeyConstraint(
            ["timestamp"],
            ["snapshots.timestamp"],
        ),
        sa.PrimaryKeyConstraint("product_id", "timestamp"),
    )
    with op.batch_alter_table("product_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_product_snapshots_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "order_books",
        sa.Column("product_id", sa.String(length=160), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("bids", sa.JSON(), nullable=False),
        sa.Column("asks", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id", "timestamp"],
            ["product_snapshots.product_id", "product_snapshots.timestamp"],
        ),
        sa.PrimaryKeyConstraint("product_id", "timestamp"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_books")
    with op.batch_alter_table("product_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_product_snapshots_timestamp")

    op.drop_table("product_snapshots")
    op.drop_table("candles")
    op.drop_table("snapshots")
    op.drop_table("products")
    # ### end Alembic commands ###
