"""Index active candle buckets"""

from alembic import op

revision = "b6e2744cf56d"
down_revision = "938168f88eae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candles", schema=None) as batch_op:
        batch_op.create_index("ix_candles_interval_bucket", ["interval", "bucket_start"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candles", schema=None) as batch_op:
        batch_op.drop_index("ix_candles_interval_bucket")

    # ### end Alembic commands ###
